# Use postgres/example user/password credentials

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://sysadmin:masterkey@db:5432/violin_site
      SECRET_KEY_BASE: 83320045917412e66b8802e067a0b356fea9a3f5b7d7d35278968f848640cb3ec9cb2ee8e72f2ce5e9b7b2a5800f4c8e059e5927de07bff00c8c5a64cc7aaf31
    ports:
      - 3000:80
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: masterkey
      POSTGRES_USER: sysadmin
      POSTGRES_DB: violin_site
    ports:
      - 5432:5432
    volumes:
      - .local/pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mydomain.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - 5050:80
    volumes:
      - .local/pgadmin:/var/lib/pgadmin
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge